name = "Raspberry Flavoured"
author = "raspmary (packwiz + tweaks by AshAxolotl)"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40ecadab9defbf582280fdbb6fba706fdf11ddcf5c19401426e75182faddea41"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"
