name = "Raspberry Flavoured"
author = "raspmary (packwiz + tweaks by AshAxolotl)"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf817542bc2d0d2241e81bae574267962cf466078bd171857c8ac1e47402f3ef"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"
unsup = "1.2.0"
