name = "Raspberry Flavoured"
author = "raspmary (packwiz + tweaks by AshAxolotl)"
version = "3.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e814a078205d2e90ec04b40181f82a2e3631bb935db9127e8cc837e6fffc39c"

[versions]
forge = "43.5.1"
minecraft = "1.19.2"
unsup = "1.2.0"
